Change the path of the pilot-agent
When debugging stuff in Istio, we should try to always use the tool
istioctl. That tool calls the pilot-agent command of the envoy proxy and
it expects it to be in the path: /usr/local/bin/pilot-agent. Otherwise,
it fails with:

Error: failed to execute command on sidecar: error execing into istio-ingressgateway-7df959db-6tmgl/istio-system istio-proxy container: command terminated with exit code 1
time="2020-06-30T18:10:00+02:00" level=error msg="exec failed: container_linux.go:349: starting container process caused \"exec: \\\"/usr/local/bin/pilot-agent\\\": stat /usr/local/bin/pilot-agent: no such file or directory\""
exec failed: container_linux.go:349: starting container process caused "exec: \"/usr/local/bin/pilot-agent\": stat /usr/local/bin/pilot-agent: no such file or directory"

Signed-off-by: Manuel Buil <mbuil@suse.com>